added custom placeholder option.
reservamos/item-quantity-dropdown pull request #46
Opened 2022-06-11 16:13 UTC by muratgorken

added custom placeholder option. Users can show placeholder if doesn't selected any item.

2022-06-11 16:34 UTC, JuanRaymundo requested changes

2022-06-11 16:34 UTC, JuanRaymundo commented on src/index.js
> +    placeHolderText: 'Custom Placeholder',
```
placeHolderText: '',
```

2022-06-11 16:39 UTC, muratgorken commented on src/index.js
> +    placeHolderText: 'Custom Placeholder',
now better than before.

2022-06-11 16:49 UTC, muratgorken commented
Can you check again? @JuanRaymundo

2022-06-11 18:11 UTC, JuanRaymundo commented
@oquis

2022-06-27 17:26 UTC, oquis requested changes

2022-06-27 17:26 UTC, oquis commented on src/index.js
> +      if (totalItems == 0 && this.placeHolderText != '') {
equality and inequality should use `===` and `!==` accordingly

2022-06-27 17:26 UTC, oquis commented on src/index.js
> +        placeHolderText: $this.data("placeholder"),
strings must use single quotes. you can check for lint errors running `yarn lint`

2022-06-27 17:26 UTC, oquis commented on README.md
> +  placeHolderText: 'Custom Placeholder',
i think `placeholder` is a better name so it matches the data-prop attribute

2025-09-03 22:56 UTC, e3matheus commented
Cerrado automáticamente (criterio: created < 2025-06-03). Añade la etiqueta "keep-open" si debe permanecer abierto.

2025-09-03 22:56 UTC, closed without merging